HT_18/item_search/item_search/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path("", include("scraper.urls")),
    path("admin/", admin.site.urls),
]

HT_18/item_search/scraper/urls.py
from django.urls import path

from . import views

app_name = "scraper"
urlpatterns = [
    path("", views.product_input, name="product_input"),
    path("products", views.ProductsListView.as_view(), name="products_list"),
    path("product/<int:pk>", views.ProductDetailView.as_view(), name="product_details"),
]

HT_18/item_search/scraper/models.py
from django.db import models

class Product(models.Model):
    product_id = models.CharField(max_length=50, unique=True, verbose_name='ID')
    name = models.CharField(max_length=255, verbose_name='Назва')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    short_description = models.TextField(blank=True, null=True, verbose_name='Короткий опис')
    brand = models.CharField(max_length=100, blank=True, null=True, verbose_name='Бренд')
    category = models.CharField(max_length=100, blank=True, null=True, verbose_name='Категорія')
    link_to_product = models.URLField(max_length=255, verbose_name='Лінк на продукт')
    update_date = models.DateTimeField(verbose_name='Дата оновлення даних')

    def __str__(self):
        return self.name


HT_18/item_search/scraper/forms.py
from django import forms
from django.core.validators import RegexValidator


class GetProductIdsForm(forms.Form):
    ids_raw_data = forms.CharField(
        label='Введіть ID продуктів, розділені комою',
        max_length=5000,
        validators=[
            RegexValidator(
                # regex=r'^[a-zA-Z\d,]+$',
                # code='invalid_input',
            ),
        ]
    )

HT_18/item_search/scraper/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic import DetailView

from .forms import GetProductIdsForm
from .models import Product
from .services import handle_valid_data


def product_input(request):
    success_message = None

    if request.method == 'POST':
        form = GetProductIdsForm(request.POST)
        if form.is_valid():
            handle_valid_data(form.cleaned_data)
            success_message = 'Дані успішно додані в чергу на обробку!'
        else:
            success_message = "Дозволені тільки латинські букви, цифри та кома!"

    form = GetProductIdsForm()
    return render(request, 'product_input.html', {'form': form, 'success_message': success_message})


class ProductsListView(ListView):
    model = Product
    template_name = "products_list.html"
    context_object_name = "products_list"
    paginate_by = 10
    ordering = ['-update_date']


class ProductDetailView(DetailView):
    model = Product
    template_name = "product_details.html"
    context_object_name = "product_details"

HT_18/item_search/scraper/templates/product_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Продукт</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #ecf0f1;
            margin: 20px;
            padding: 20px;
        }

        h2 {
            color: #333;
            text-align: center;
        }

        p {
            color: #333;
            margin-bottom: 10px;
        }

        strong {
            color: #3498db;
        }

        a {
            color: #3498db;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }

        .back-links {
            margin-top: 20px;
            text-align: center;
        }

        .back-links a {
            color: #3498db;
            text-decoration: none;
            margin-right: 20px;
        }
    </style>
</head>
<body>

<h2>{{ product_details.name }}</h2>
<p><strong>Ціна:</strong> {{ product_details.price }}</p>
<p><strong>Короткий опис:</strong> {{ product_details.short_description }}</p>
<p><strong>Бренд:</strong> {{ product_details.brand }}</p>
<p><strong>Категорія:</strong> {{ product_details.category }}</p>
<p><strong>Лінк на продукт:</strong> <a href="{{ product_details.link_to_product }}">{{ product_details.link_to_product }}</a></p>
<p><strong>Дата оновлення:</strong> {{ product_details.update_date|date:"d.m.Y H:i" }}</p>

<div class="back-links">
    <p><a href="{% url 'scraper:product_input' %}">Додати продукти</a></p>
    <p><a href="{% url 'scraper:products_list' %}">Мої продукти</a></p>
</div>

</body>
</html>

HT_18/item_search/scraper/templates/product_input.html
<!DOCTYPE html>
<html>
<head>
    <title>Додати продукти</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #ecf0f1;
            margin: 20px;
            padding: 20px;
        }

        h2 {
            color: #333;
            text-align: center;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin-top: 20px;
        }

        .form-field {
            margin-bottom: 10px;
        }

        button {
            background-color: #3498db;
            color: #fff;
            padding: 10px;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        button:hover {
            background-color: #2980b9;
        }

        .success-message {
            margin-top: 10px;
            padding: 10px;
            text-align: center;
            border-radius: 5px;
            font-weight: bold;
        }

        .success-green {
            background-color: #27ae60;
            color: #fff;
        }

        .success-red {
            background-color: #e74c3c;
            color: #fff;
        }

        .back-to-list {
            margin-top: 20px;
            text-align: center;
        }

        .back-to-list a {
            color: #3498db;
            text-decoration: none;
        }
    </style>
    <script>
        function hideMessage() {
            var successMessage = document.getElementById('success-message');
            successMessage.style.display = 'none';
        }

        window.onload = function() {
            var successMessage = document.getElementById('success-message');
            if (successMessage) {
                setTimeout(hideMessage, 1500);  // Ховаємо повідомлення через 1,5 секунди (1500 мілісекунд)
            }
        };
    </script>
</head>
<body>

<h2>Додати продукти в базу збережених</h2>

<form method="post" action="{% url 'scraper:product_input' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Відправити</button>

    {% if success_message %}
        <div id="success-message" class="success-message
        {% if success_message == 'Дані успішно відправлені!' %}success-green
        {% elif success_message == 'Дозволені тільки цифри та кома!' %}success-red
        {% endif %}">
            <p>{{ success_message }}</p>
        </div>
    {% endif %}

</form>

<div class="back-to-list">
    <p><a href="{% url 'scraper:products_list' %}">Список продуктів</a></p>
</div>

</body>
</html>

HT_18/item_search/scraper/templates/products_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Мої продукти</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f9f9f9;
            margin: 20px;
            padding: 20px;
        }

        h2 {
            color: #333;
            text-align: center;
        }

        table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #3498db;
            color: #fff;
        }

        .pagination {
            text-align: center;
            margin-top: 20px;
        }

        .step-links {
            display: inline-block;
        }

        .step-links a {
            margin-right: 12px;
            color: #3498db;
            text-decoration: none;
        }

        .current {
            margin-right: 12px;
            font-weight: bold;
            color: #333;
        }

        .add-product-link {
            display: block;
            margin-top: 20px;
            text-align: center;
        }

        .add-product-link a {
            color: #27ae60;
            text-decoration: none;
        }
    </style>
</head>
<body>

<h2>Ваш список продуктів</h2>

<table>
    <thead>
    <tr>
        <th>Назва</th>
        <th>Ціна</th>
        <th>Дата оновлення даних</th>
    </tr>
    </thead>
    <tbody>
    {% for product in products_list %}
        <tr>
            <td><a href="{% url 'scraper:product_details' pk=product.pk %}" style="color: #3498db;">{{ product.name }}</a></td>
            <td style="color: #2ecc71;">{{ product.price }}</td>
            <td style="color: #333;">{{ scraper.update_date|date:"d.m.Y H:i" }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<div class="pagination">
    <span class="step-links">
        <br><br>
        {% if page_obj.has_previous %}
            <a href="?page=1" style="color: #3498db;">&laquo; перша</a>
            <span style="margin-right: 12px;"></span>
            <a href="?page={{ page_obj.previous_page_number }}" style="color: #3498db;">&laquo; попередня</a>
            <span style="margin-right: 12px;"></span>
        {% endif %}

        <span class="current" style="color: #333;">
            Сторінка {{ page_obj.number }} з {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <span style="margin-right: 12px;"></span>
            <a href="?page={{ page_obj.next_page_number }}" style="color: #3498db;">наступна &raquo;</a>
            <span style="margin-right: 12px;"></span>
            <a href="?page={{ page_obj.paginator.num_pages }}" style="color: #3498db;">остання &raquo;</a>
        {% endif %}
    </span>
</div>

<div class="add-product-link">
    <p><a href="{% url 'scraper:product_input' %}" style="color: #27ae60;">Повернутися до додавання продукти</a></p>
</div>

</body>
</html>